@echo off
:loop
start error.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error4.vbs
start error5.vbs
start error6.vbs
start error7.vbs
start error8.vbs
start error9.vbs
start error10.vbs
start error.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error4.vbs
start error5.vbs
start error6.vbs
start error7.vbs
start error5.vbs
start error10.vbs
start error.vbs
start error7.vbs
start error8.vbs
start error9.vbs
start error10.vbs
start error.vbs
start error5.vbs
start error6.vbs
start error7.vbs
start error5.vbs
start error10.vbs
start error.vbs
start error7.vbs
start error8.vbs
start error9.vbs
start error10.vbs
start error.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error4.vbs
start error5.vbs
start error6.vbs
start error7.vbs
start error5.vbs
start error10.vbs
start error.vbs
start error1.vbs
start error6.vbs
start error7.vbs
start error8.vbs
start error9.vbs
start error10.vbs
start error4.vbs
start error3.vbs
start error4.vbs
start error10.vbs
start error.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error4.vbs
start error5.vbs
start error6.vbs
start error.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error4.vbs
start error5.vbs
start error6.vbs
start error7.vbs
start error8.vbs
start error9.vbs
start error10.vbs
start error.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error4.vbs
start error5.vbs
start error6.vbs
start error7.vbs
start error5.vbs
start error10.vbs
start error.vbs
start error1.vbs
start error6.vbs
start error7.vbs
start error8.vbs
start error9.vbs
start error10.vbs
start error4.vbs
start error3.vbs
start error4.vbs
start error10.vbs
start error.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error4.vbs
start error5.vbs
start error6.vbs
start error.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error4.vbs
start error5.vbs
start error3.vbs
start error4.vbs
start error5.vbs
start error6.vbs
start error.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error4.vbs
start error5.vbs
start error6.vbs
start error.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error4.vbs
start error5.vbs
start error3.vbs
start error4.vbs
start error5.vbs
start error6.vbs
start error.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error4.vbs
start error5.vbs
start error6.vbs
start error7.vbs
start error8.vbs
start error9.vbs
start error10.vbs
start error.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error4.vbs
start error5.vbs
start error6.vbs
start error7.vbs
start error5.vbs
start error10.vbs
start error.vbs
start error1.vbs
start error6.vbs
start error7.vbs
start error8.vbs
start error9.vbs
start error10.vbs
start error4.vbs
start error3.vbs
start error4.vbs
start error10.vbs
start error.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error4.vbs
start error5.vbs
start error6.vbs
start error.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error4.vbs
start error5.vbs
start error6.vbs
start error7.vbs
start error8.vbs
start error9.vbs
start error10.vbs
start error.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error4.vbs
start error5.vbs
start error6.vbs
start error7.vbs
start error5.vbs
start error10.vbs
start error.vbs
start error1.vbs
start error6.vbs
start error7.vbs
start error8.vbs
start error9.vbs
start error10.vbs
start error4.vbs
start error3.vbs
start error4.vbs
start error10.vbs
start error.vbs
start error1.vbs
start error2.vbs
start error3.vbs
start error4.vbs
start error5.vbs
start error6.vbs
goto loop